"""
Curated seed companies list for ATS registry builder.
Contains 150+ tech companies to ensure 100+ validated ATS boards pass verification.
"""

SEED_COMPANIES = [
    # --- GREENHOUSE ---
    {"company": "Razorpay", "platform": "greenhouse", "token": "razorpaysoftwareprivatelimited", "category": "startup", "country": "India"},
    {"company": "Airbnb", "platform": "greenhouse", "token": "airbnb", "category": "product", "country": "Global"},
    {"company": "Lyft", "platform": "greenhouse", "token": "lyft", "category": "product", "country": "Global"},
    {"company": "Pinterest", "platform": "greenhouse", "token": "pinterest", "category": "product", "country": "Global"},
    {"company": "Instacart", "platform": "greenhouse", "token": "instacart", "category": "product", "country": "Global"},
    {"company": "Figma", "platform": "greenhouse", "token": "figma", "category": "product", "country": "Global"},
    {"company": "Reddit", "platform": "greenhouse", "token": "reddit", "category": "product", "country": "Global"},
    {"company": "Coinbase", "platform": "greenhouse", "token": "coinbase", "category": "product", "country": "Global"},
    {"company": "Discord", "platform": "greenhouse", "token": "discord", "category": "product", "country": "Global"},
    {"company": "Databricks", "platform": "greenhouse", "token": "databricks", "category": "product", "country": "Global"},
    {"company": "MongoDB", "platform": "greenhouse", "token": "mongodb", "category": "product", "country": "Global"},
    {"company": "GitLab", "platform": "greenhouse", "token": "gitlab", "category": "product", "country": "Global"},
    {"company": "Datadog", "platform": "greenhouse", "token": "datadog", "category": "product", "country": "Global"},
    {"company": "Cloudflare", "platform": "greenhouse", "token": "cloudflare", "category": "product", "country": "Global"},
    {"company": "Vercel", "platform": "greenhouse", "token": "vercel", "category": "product", "country": "Global"},
    {"company": "Scale AI", "platform": "greenhouse", "token": "scaleai", "category": "startup", "country": "Global"},
    {"company": "Brex", "platform": "greenhouse", "token": "brex", "category": "startup", "country": "Global"},
    {"company": "Chime", "platform": "greenhouse", "token": "chime", "category": "startup", "country": "Global"},
    {"company": "Affirm", "platform": "greenhouse", "token": "affirm", "category": "product", "country": "Global"},
    {"company": "Gusto", "platform": "greenhouse", "token": "gusto", "category": "product", "country": "Global"},
    {"company": "Robinhood", "platform": "greenhouse", "token": "robinhood", "category": "product", "country": "Global"},
    {"company": "Webflow", "platform": "greenhouse", "token": "webflow", "category": "product", "country": "Global"},
    {"company": "Duolingo", "platform": "greenhouse", "token": "duolingo", "category": "product", "country": "Global"},
    {"company": "Remote", "platform": "greenhouse", "token": "remote", "category": "startup", "country": "Global"},
    {"company": "InMobi", "platform": "greenhouse", "token": "inmobi", "category": "product", "country": "India"},
    {"company": "Druva", "platform": "greenhouse", "token": "druva", "category": "product", "country": "India"},
    {"company": "Rubrik", "platform": "greenhouse", "token": "rubrik", "category": "product", "country": "India"},
    {"company": "Pure Storage", "platform": "greenhouse", "token": "purestorage", "category": "product", "country": "Global"},
    {"company": "Stripe", "platform": "greenhouse", "token": "stripe", "category": "product", "country": "Global"},
    {"company": "Asana", "platform": "greenhouse", "token": "asana", "category": "product", "country": "Global"},
    {"company": "Airtable", "platform": "greenhouse", "token": "airtable", "category": "product", "country": "Global"},
    {"company": "Dropbox", "platform": "greenhouse", "token": "dropbox", "category": "product", "country": "Global"},
    {"company": "Squarespace", "platform": "greenhouse", "token": "squarespace", "category": "product", "country": "Global"},
    {"company": "Fastly", "platform": "greenhouse", "token": "fastly", "category": "product", "country": "Global"},
    {"company": "Zscaler", "platform": "greenhouse", "token": "zscaler", "category": "product", "country": "Global"},
    {"company": "Okta", "platform": "greenhouse", "token": "okta", "category": "product", "country": "Global"},
    {"company": "MinIO", "platform": "greenhouse", "token": "minio", "category": "startup", "country": "Global"},
    {"company": "Amplitude", "platform": "greenhouse", "token": "amplitude", "category": "product", "country": "Global"},
    {"company": "Mixpanel", "platform": "greenhouse", "token": "mixpanel", "category": "product", "country": "Global"},
    {"company": "Braze", "platform": "greenhouse", "token": "braze", "category": "product", "country": "Global"},
    {"company": "Qualtrics", "platform": "greenhouse", "token": "qualtrics", "category": "product", "country": "Global"},
    {"company": "Neo4j", "platform": "greenhouse", "token": "neo4j", "category": "product", "country": "Global"},
    {"company": "SingleStore", "platform": "greenhouse", "token": "singlestore", "category": "product", "country": "Global"},
    {"company": "Slice", "platform": "greenhouse", "token": "slice", "category": "startup", "country": "India"},
    {"company": "Groww", "platform": "greenhouse", "token": "groww", "category": "startup", "country": "India"},
    {"company": "ThoughtWorks", "platform": "greenhouse", "token": "thoughtworks", "category": "services", "country": "India"},
    {"company": "SoFi", "platform": "greenhouse", "token": "sofi", "category": "product", "country": "Global"},
    {"company": "Toast", "platform": "greenhouse", "token": "toast", "category": "product", "country": "Global"},
    {"company": "Navan (TripActions)", "platform": "greenhouse", "token": "tripactions", "category": "product", "country": "Global"},
    {"company": "Bill.com", "platform": "greenhouse", "token": "billcom", "category": "product", "country": "Global"},
    {"company": "New Relic", "platform": "greenhouse", "token": "newrelic", "category": "product", "country": "Global"},
    {"company": "Mercury", "platform": "greenhouse", "token": "mercury", "category": "startup", "country": "Global"},
    {"company": "Sumo Logic", "platform": "greenhouse", "token": "sumologic", "category": "product", "country": "Global"},
    {"company": "Fivetran", "platform": "greenhouse", "token": "fivetran", "category": "product", "country": "Global"},
    {"company": "Dremio", "platform": "greenhouse", "token": "dremio", "category": "product", "country": "Global"},
    {"company": "Starburst", "platform": "greenhouse", "token": "starburst", "category": "product", "country": "Global"},
    {"company": "Collibra", "platform": "greenhouse", "token": "collibra", "category": "product", "country": "Global"},
    {"company": "Hightouch", "platform": "greenhouse", "token": "hightouch", "category": "startup", "country": "Global"},
    {"company": "Twilio", "platform": "greenhouse", "token": "twilio", "category": "product", "country": "Global"},
    {"company": "Tigera", "platform": "greenhouse", "token": "tigera", "category": "startup", "country": "Global"},
    {"company": "Canonical", "platform": "greenhouse", "token": "canonical", "category": "product", "country": "Global"},
    {"company": "Astranis", "platform": "greenhouse", "token": "astranis", "category": "startup", "country": "Global"},
    {"company": "Rocket Lab", "platform": "greenhouse", "token": "rocketlab", "category": "product", "country": "Global"},
    {"company": "SpaceX", "platform": "greenhouse", "token": "spacex", "category": "product", "country": "Global"},
    {"company": "Relativity Space", "platform": "greenhouse", "token": "relativity", "category": "startup", "country": "Global"},
    {"company": "Spire", "platform": "greenhouse", "token": "spire", "category": "product", "country": "Global"},
    {"company": "LaunchDarkly", "platform": "greenhouse", "token": "launchdarkly", "category": "product", "country": "Global"},
    {"company": "Iterable", "platform": "greenhouse", "token": "iterable", "category": "product", "country": "Global"},
    {"company": "Klaviyo", "platform": "greenhouse", "token": "klaviyo", "category": "product", "country": "Global"},
    {"company": "PagerDuty", "platform": "greenhouse", "token": "pagerduty", "category": "product", "country": "Global"},
    {"company": "Grafana Labs", "platform": "greenhouse", "token": "grafanalabs", "category": "product", "country": "Global"},
    {"company": "Honeycomb", "platform": "greenhouse", "token": "honeycomb", "category": "product", "country": "Global"},

    # --- LEVER ---
    {"company": "Spotify", "platform": "lever", "token": "spotify", "category": "product", "country": "Global"},
    {"company": "Palantir", "platform": "lever", "token": "palantir", "category": "product", "country": "Global"},

    # --- ASHBY ---
    {"company": "OpenAI", "platform": "ashby", "token": "openai", "category": "product", "country": "Global"},
    {"company": "Ramp", "platform": "ashby", "token": "ramp", "category": "startup", "country": "Global"},
    {"company": "Linear", "platform": "ashby", "token": "linear", "category": "startup", "country": "Global"},
    {"company": "Airwallex", "platform": "ashby", "token": "airwallex", "category": "startup", "country": "Global"},
    {"company": "Supabase", "platform": "ashby", "token": "supabase", "category": "startup", "country": "Global"},
    {"company": "Modal", "platform": "ashby", "token": "modal", "category": "startup", "country": "Global"},
    {"company": "ElevenLabs", "platform": "ashby", "token": "elevenlabs", "category": "startup", "country": "Global"},
    {"company": "Perplexity", "platform": "ashby", "token": "perplexity", "category": "startup", "country": "Global"},
    {"company": "PostHog", "platform": "ashby", "token": "posthog", "category": "startup", "country": "Global"},
    {"company": "Vanta", "platform": "ashby", "token": "vanta", "category": "startup", "country": "Global"},
    {"company": "Railway", "platform": "ashby", "token": "railway", "category": "startup", "country": "Global"},
    {"company": "Resend", "platform": "ashby", "token": "resend", "category": "startup", "country": "Global"},
    {"company": "LangChain", "platform": "ashby", "token": "langchain", "category": "startup", "country": "Global"},
    {"company": "Pinecone", "platform": "ashby", "token": "pinecone", "category": "startup", "country": "Global"},
    {"company": "Zapier (Ashby)", "platform": "ashby", "token": "zapier", "category": "product", "country": "Global"},
    {"company": "Quora", "platform": "ashby", "token": "quora", "category": "product", "country": "Global"},
    {"company": "Synthesia", "platform": "ashby", "token": "synthesia", "category": "startup", "country": "Global"},
    {"company": "Replit", "platform": "ashby", "token": "replit", "category": "startup", "country": "Global"},
    {"company": "Decagon", "platform": "ashby", "token": "decagon", "category": "startup", "country": "Global"},
    {"company": "Harvey AI", "platform": "ashby", "token": "harvey", "category": "startup", "country": "Global"},
    {"company": "Runway AI", "platform": "ashby", "token": "runway", "category": "startup", "country": "Global"},
    {"company": "Character.AI", "platform": "ashby", "token": "character", "category": "startup", "country": "Global"},
    {"company": "Sentry (Ashby)", "platform": "ashby", "token": "sentry", "category": "product", "country": "Global"},
    {"company": "Pika", "platform": "ashby", "token": "pika", "category": "startup", "country": "Global"},
    {"company": "Ideogram", "platform": "ashby", "token": "ideogram", "category": "startup", "country": "Global"},
    {"company": "Cohere", "platform": "ashby", "token": "cohere", "category": "startup", "country": "Global"},

    # --- WORKDAY ---
    {"company": "Adobe", "platform": "workday", "token": "adobe", "domain": "adobe.wd5.myworkdayjobs.com", "site": "external_experienced", "category": "enterprise", "country": "India"},
    {"company": "Nvidia", "platform": "workday", "token": "nvidia", "domain": "nvidia.wd5.myworkdayjobs.com", "site": "NVIDIAExternalCareerSite", "category": "enterprise", "country": "Global"},
    {"company": "Salesforce", "platform": "workday", "token": "salesforce", "domain": "salesforce.wd12.myworkdayjobs.com", "site": "External_Career_Site", "category": "enterprise", "country": "India"},
    {"company": "Workday", "platform": "workday", "token": "workday", "domain": "workday.wd5.myworkdayjobs.com", "site": "Workday", "category": "enterprise", "country": "Global"},
    {"company": "Autodesk", "platform": "workday", "token": "autodesk", "domain": "autodesk.wd1.myworkdayjobs.com", "site": "Ext", "category": "enterprise", "country": "Global"},
]
